
apiVersion: v2
name: kubedash
description: "KubeDash is a general purpose, web-based UI for Kubernetes clusters."
type: application
version: 3.1.0
appVersion: "3.1.0"
kubeVersion: ">=1.19.x-0"
keywords:
  - kubedash
  - kubernetes dashboard
  - trivy-operator
home: https://github.com/devopstales/kubedash
icon: https://raw.githubusercontent.com/devopstales/helm-charts/main/icons/kubectl-login.png
sources:
  - https://github.com/devopstales/kubedash
  - https://github.com/devopstales/helm-charts
deprecated: false

dependencies:
  - name: redis
    version: ">=21.1.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: postgresql
    version: ">=11.9.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: metrics-server
    version: "3.8.4"
    repository: "https://kubernetes-sigs.github.io/metrics-server/"
    condition: metricsServer.enabled
