apiVersion: v1
kind: "LimitRange"
metadata:
  name: "limits"
  namespace: network-testing
spec:
 limits:
   - type: "Container"
     default:
       cpu: "200m"
       memory: "256Mi"
     defaultRequest:
       cpu: "100m"
       memory: "100Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: storagelimits
  namespace: network-testing
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 2Gi
    min:
      storage: 1Gi
---
apiVersion: v1
kind: ResourceQuota
metadata:
 name: compute-quota
 namespace: network-testing
spec:
 hard:
   requests.cpu: '8'
   requests.memory: 32Gi
   limits.cpu: '8'
   limits.memory: 32Gi
 scopes:
 - NotTerminating
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pods-low
  namespace: network-testing
spec:
  hard:
    cpu: "5"
    memory: 10Gi
    pods: "10"
  scopeSelector:
    matchExpressions:
    - operator : In
      scopeName: PriorityClass
      values: ["low"]
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storagequota
spec:
  hard:
    persistentvolumeclaims: "5"
    requests.storage: "5Gi"

