apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "kubedash.fullname" . }}
  labels:
    app: kubedash
    {{- include "kubedash.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kubedash
      {{- include "kubedash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: kubedash
        {{- include "kubedash.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubedash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        env:
          - name: TZ
            value: {{ .Values.TimeZone }}
          - name: FLASK_CONFIG
            value: "{{ .Values.flaskConfig }}"
{{- if or (eq .Values.logLevel "DEBUG") (eq .Values.logLevel "HIGH") }}
          - name: VERBOSE_LOG
            value: "True"
{{- end }}
        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 1
        ports:
        - containerPort: 8000
          protocol: TCP
          name: http