{{- if not .Values.route.enabled -}}
{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: kubedash
    {{- include "kubedash.labels" . | nindent 4 }}
  name: {{ include "kubedash.fullname" . }}-ingress-route
spec:
  host: {{ .Values.ingress.url }}
  port:
    targetPort: 8000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name:  {{ include "kubedash.fullname" . }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - status: 'True'
          type: Admitted
      host: {{ .Values.ingress.url }}
      routerName: {{ include "kubedash.fullname" . }}-ingress-route
      wildcardPolicy: None
{{- end }}
{{- end }}