apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubedash.fullname" . }}
  labels:
    app: kubedash
    {{- include "kubedash.labels" . | nindent 4 }}
spec:
  selector:
    app: kubedash
    {{- include "kubedash.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}