"""create sessions table

Revision ID: 39704d8c644a
Revises: d372484d86c9
Create Date: 2023-07-28 10:54:30.755177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39704d8c644a'
down_revision = 'd372484d86c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
