"""add: metrics tables

Revision ID: 5062431c2bac
Revises: f84ec038286c
Create Date: 2025-03-08 17:07:21.028498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5062431c2bac'
down_revision = 'f84ec038286c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metrics_nodes',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('memory', sa.Float(), nullable=False),
    sa.Column('storage', sa.Float(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('metrics_pods',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('container', sa.String(length=255), nullable=False),
    sa.Column('cpu', sa.Float(), nullable=False),
    sa.Column('memory', sa.Float(), nullable=False),
    sa.Column('storage', sa.Float(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics_pods')
    op.drop_table('metrics_nodes')
    # ### end Alembic commands ###
