"""add: ai-chat models

Revision ID: 51362c3e6384
Revises: ea51eddbcfb6
Create Date: 2026-03-10 11:08:33.672810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51362c3e6384'
down_revision = 'ea51eddbcfb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_results', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Drop unique constraint on application_catalog.application_url (skip if doesn't exist, e.g., SQLite)
    bind = op.get_bind()
    if bind.dialect.name == 'sqlite':
        # SQLite doesn't support dropping unique constraints via ALTER TABLE
        # The constraint is enforced by the column definition itself
        pass
    else:
        with op.batch_alter_table('application_catalog', schema=None) as batch_op:
            try:
                batch_op.drop_constraint(batch_op.f('application_catalog_application_url_key'), type_='unique')
            except ValueError:
                pass  # Constraint doesn't exist

    with op.batch_alter_table('registry_events', schema=None) as batch_op:
        try:
            batch_op.create_unique_constraint('uq_registry_events_id', ['id'])
        except Exception:
            pass  # Constraint may already exist

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registry_events', schema=None) as batch_op:
        try:
            batch_op.drop_constraint('uq_registry_events_id', type_='unique')
        except Exception:
            pass  # Constraint may not exist

    bind = op.get_bind()
    if bind.dialect.name != 'sqlite':
        with op.batch_alter_table('application_catalog', schema=None) as batch_op:
            try:
                batch_op.create_unique_constraint(batch_op.f('application_catalog_application_url_key'), ['application_url'])
            except Exception:
                pass

    op.drop_table('ai_chat_messages')
    op.drop_table('ai_chat_conversations')
    # ### end Alembic commands ###
