"""add: ai-chat models

Revision ID: 51362c3e6384
Revises: ea51eddbcfb6
Create Date: 2026-03-10 11:08:33.672810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51362c3e6384'
down_revision = 'ea51eddbcfb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tool_calls', sa.JSON(), nullable=True),
    sa.Column('tool_results', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_chat_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_catalog', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('application_catalog_application_url_key'), type_='unique')

    with op.batch_alter_table('registry_events', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registry_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('application_catalog', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('application_catalog_application_url_key'), ['application_url'])

    op.drop_table('ai_chat_messages')
    op.drop_table('ai_chat_conversations')
    # ### end Alembic commands ###
