"""users table

Revision ID: 7253f5a7bfda
Revises: 
Create Date: 2023-03-14 08:48:49.176178

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7253f5a7bfda'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k8s_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('k8s_server_url', sa.Text(), nullable=False),
    sa.Column('k8s_context', sa.Text(), nullable=False),
    sa.Column('k8s_server_ca', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('k8s_context'),
    sa.UniqueConstraint('k8s_server_url')
    )
    op.create_table('openid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oauth_server_uri', sa.Text(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('client_secret', sa.Text(), nullable=False),
    sa.Column('base_uri', sa.Text(), nullable=False),
    sa.Column('scope', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('oauth_server_uri')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=80), nullable=True),
    sa.Column('user_type', sa.String(length=5), nullable=False),
    sa.Column('tokens', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('openid')
    op.drop_table('k8s_config')
    # ### end Alembic commands ###
