"""registry_event table

Revision ID: d372484d86c9
Revises: 5598d31e675a
Create Date: 2023-04-26 18:18:28.570849

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd372484d86c9'
down_revision = '5598d31e675a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registry_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=4), nullable=False),
    sa.Column('repository', sa.String(length=100), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('digest', sa.String(length=100), nullable=False),
    sa.Column('ip', sa.String(length=15), nullable=False),
    sa.Column('user', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registry_events')
    # ### end Alembic commands ###
