"""issuer_ca for sso server

Revision ID: da8ef7e783f7
Revises: 5062431c2bac
Create Date: 2025-06-17 13:39:42.014526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da8ef7e783f7'
down_revision = '5062431c2bac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openid', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_server_ca', sa.Text(), nullable=True))

    with op.batch_alter_table('registry_events', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registry_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('openid', schema=None) as batch_op:
        batch_op.drop_column('oauth_server_ca')

    # ### end Alembic commands ###
