"""plugin: application catalog

Revision ID: ea51eddbcfb6
Revises: 22fb365284ec
Create Date: 2025-07-21 20:45:31.546592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea51eddbcfb6'
down_revision = '22fb365284ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(length=100), nullable=False),
    sa.Column('application_enabled', sa.Boolean(), nullable=False),
    sa.Column('application_url', sa.String(length=200), nullable=False),
    sa.Column('application_icon', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_name'),
    sa.UniqueConstraint('application_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_catalog')
    # ### end Alembic commands ###
