apiVersion: skaffold/v2beta19
kind: Config
build:
  local: {}
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: kubedash
      context: ../../docker/kubedash/
      #docker:
      #  dockerfile: ../../docker/kubedash/Dockerfile
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ../../deploy/kubernetes/03_deployment.yaml
    defaultNamespace: balazs-paldi
# use the cloudbuild profile to build images using Google Cloud Build
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}

    ## https://skaffold.dev/docs/deployers/helm/