apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: users.kubedash.devopstales.io
spec:
  group: kubedash.devopstales.io
  scope: Cluster
  names:
    plural: users
    singular: user
    kind: User
    shortNames:
      - usr
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                fullName:
                  type: string
                identities:
                  type: array
                  items:
                    type: string
                groups:
                  type: array
                  items:
                    type: string

