apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmcharts.helm.cattle.io
spec:
  group: helm.cattle.io
  names:
    kind: HelmChart
    plural: helmcharts
    singular: helmchart
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.jobName
      name: Job
      type: string
    - jsonPath: .spec.chart
      name: Chart
      type: string
    - jsonPath: .spec.targetNamespace
      name: TargetNamespace
      type: string
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .spec.repo
      name: Repo
      type: string
    - jsonPath: .spec.helmVersion
      name: HelmVersion
      type: string
    - jsonPath: .spec.bootstrap
      name: Bootstrap
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              authPassCredentials:
                type: boolean
              authSecret:
                nullable: true
                properties:
                  name:
                    nullable: true
                    type: string
                type: object
              backOffLimit:
                nullable: true
                type: integer
              bootstrap:
                type: boolean
              chart:
                nullable: true
                type: string
              chartContent:
                nullable: true
                type: string
              createNamespace:
                type: boolean
              dockerRegistrySecret:
                nullable: true
                properties:
                  name:
                    nullable: true
                    type: string
                type: object
              failurePolicy:
                nullable: true
                type: string
              helmVersion:
                nullable: true
                type: string
              insecureSkipTLSVerify:
                type: boolean
              jobImage:
                nullable: true
                type: string
              plainHTTP:
                type: boolean
              podSecurityContext:
                nullable: true
                properties:
                  appArmorProfile:
                    nullable: true
                    properties:
                      localhostProfile:
                        nullable: true
                        type: string
                      type:
                        nullable: true
                        type: string
                    type: object
                  fsGroup:
                    nullable: true
                    type: integer
                  fsGroupChangePolicy:
                    nullable: true
                    type: string
                  runAsGroup:
                    nullable: true
                    type: integer
                  runAsNonRoot:
                    nullable: true
                    type: boolean
                  runAsUser:
                    nullable: true
                    type: integer
                  seLinuxOptions:
                    nullable: true
                    properties:
                      level:
                        nullable: true
                        type: string
                      role:
                        nullable: true
                        type: string
                      type:
                        nullable: true
                        type: string
                      user:
                        nullable: true
                        type: string
                    type: object
                  seccompProfile:
                    nullable: true
                    properties:
                      localhostProfile:
                        nullable: true
                        type: string
                      type:
                        nullable: true
                        type: string
                    type: object
                  supplementalGroups:
                    items:
                      type: integer
                    nullable: true
                    type: array
                  supplementalGroupsPolicy:
                    nullable: true
                    type: string
                  sysctls:
                    items:
                      properties:
                        name:
                          nullable: true
                          type: string
                        value:
                          nullable: true
                          type: string
                      type: object
                    nullable: true
                    type: array
                  windowsOptions:
                    nullable: true
                    properties:
                      gmsaCredentialSpec:
                        nullable: true
                        type: string
                      gmsaCredentialSpecName:
                        nullable: true
                        type: string
                      hostProcess:
                        nullable: true
                        type: boolean
                      runAsUserName:
                        nullable: true
                        type: string
                    type: object
                type: object
              repo:
                nullable: true
                type: string
              repoCA:
                nullable: true
                type: string
              repoCAConfigMap:
                nullable: true
                properties:
                  name:
                    nullable: true
                    type: string
                type: object
              securityContext:
                nullable: true
                properties:
                  allowPrivilegeEscalation:
                    nullable: true
                    type: boolean
                  appArmorProfile:
                    nullable: true
                    properties:
                      localhostProfile:
                        nullable: true
                        type: string
                      type:
                        nullable: true
                        type: string
                    type: object
                  capabilities:
                    nullable: true
                    properties:
                      add:
                        items:
                          nullable: true
                          type: string
                        nullable: true
                        type: array
                      drop:
                        items:
                          nullable: true
                          type: string
                        nullable: true
                        type: array
                    type: object
                  privileged:
                    nullable: true
                    type: boolean
                  procMount:
                    nullable: true
                    type: string
                  readOnlyRootFilesystem:
                    nullable: true
                    type: boolean
                  runAsGroup:
                    nullable: true
                    type: integer
                  runAsNonRoot:
                    nullable: true
                    type: boolean
                  runAsUser:
                    nullable: true
                    type: integer
                  seLinuxOptions:
                    nullable: true
                    properties:
                      level:
                        nullable: true
                        type: string
                      role:
                        nullable: true
                        type: string
                      type:
                        nullable: true
                        type: string
                      user:
                        nullable: true
                        type: string
                    type: object
                  seccompProfile:
                    nullable: true
                    properties:
                      localhostProfile:
                        nullable: true
                        type: string
                      type:
                        nullable: true
                        type: string
                    type: object
                  windowsOptions:
                    nullable: true
                    properties:
                      gmsaCredentialSpec:
                        nullable: true
                        type: string
                      gmsaCredentialSpecName:
                        nullable: true
                        type: string
                      hostProcess:
                        nullable: true
                        type: boolean
                      runAsUserName:
                        nullable: true
                        type: string
                    type: object
                type: object
              set:
                additionalProperties:
                  x-kubernetes-int-or-string: true
                nullable: true
                type: object
              targetNamespace:
                nullable: true
                type: string
              timeout:
                nullable: true
                type: string
              valuesContent:
                nullable: true
                type: string
              version:
                nullable: true
                type: string
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    message:
                      nullable: true
                      type: string
                    reason:
                      nullable: true
                      type: string
                    status:
                      nullable: true
                      type: string
                    type:
                      nullable: true
                      type: string
                  type: object
                nullable: true
                type: array
              jobName:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helmchartconfigs.helm.cattle.io
spec:
  group: helm.cattle.io
  names:
    kind: HelmChartConfig
    plural: helmchartconfigs
    singular: helmchartconfig
  preserveUnknownFields: false
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              failurePolicy:
                nullable: true
                type: string
              valuesContent:
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  labels:
#    app: helm-controller
#  name: helm-controller
#  namespace: cluster-system
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: helm-controller
#  template:
#    metadata:
#      labels:
#        app: helm-controller
#    spec:
#      containers:
#      - command:
#        - helm-controller
#        image: rancher/helm-controller:v0.16.6
#        name: helm-controller
#---
