version: 2
project_name: kubectl-kdlogin
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    id: "kdlogin"
    binary: kubectl-kdlogin

archives:
  - formats: [ 'tar.gz' ]
    # this name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
    - goos: windows
      formats: ['zip']

#chocolateys:
#  - name: kubectl-login
#    owners: devopstales
#    authors: devopstales
#    title: "kubectl-login (CLI)"
#    project_url: "https://devopstales.github.io"
#    icon_url: "https://cdn.jsdelivr.net/gh/devopstales/helm-charts@master/icons/kubectl-login.png"
#    url_template: "https://github.com/devopstales/KubeDash/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
#    copyright: 2023 devopstales
#    license_url: "https://github.com/devopstales/KubeDash/blob/main/LICENSE"
#    require_license_acceptance: false
#    project_source_url: "https://github.com/devopstales/KubeDash"
#    docs_url: "https://devopstales.github.io/KubeDash/"
#    bug_tracker_url: "https://github.com/devopstales/KubeDash/issues"
#    tags: "kubectl-login kubernetes kubelogin authentication oidc cli foss cross-platform KubeDash"
#    summary: "Kubernetes OIDC authentication"
#    description: |
#      kubectl-login is a kubectl plugin that can be used to easily enable authentication flows via OIDC for a kubernetes cluster. Usage: ```kubectl login kubedash_url```
#    release_notes: "https://github.com/devopstales/KubeDash/releases/tag/{{ .Version }}"
#    api_key: '{{ .Env.CHOCO_TOKEN }}'
#    skip_publish: true

brews:
  - name: kdlogin
    repository:
      owner: devopstales
      name: homebrew-devopstales
    homepage: "https://devopstales.github.io"
    license: "Apache 2.0"
    description: "kubectl-kdlogin is a kubectl plugin that can be used to easily enable authentication flows via OIDC for a kubernetes cluster."
    conflicts:
      - login
      - dtlogin
      - kubectl-login
      - oidc-login
    install: |
      bin.install "kubectl-kdlogin"

krews:
  - name: kdlogin
    repository:
      owner: devopstales
      name: krew
    homepage: "https://devopstales.github.io"
    short_description: "Login to a cluster via openid-connect"
    description: |
      Run `kubectl kdlogin <kubedash-ingress-url>`.
      It automatically opens the browser and you can log in to the provider.
      After authentication, it writes the token to the kubeconfig and you can access the cluster.
    caveats: |
      1) You need to install the kubedash server by helm:
          helm repo add devopstales https://devopstales.github.io/helm-charts
          helm repo update
          kubectl create ns kubedash
          kubens kubedash
          helm upgrade --install kubedash devopstales/kubedash -f values.yaml
      2) You need to setup the OIDC provider at Kubernetes API server.
          nano /etc/kubernetes/manifests/kube-apiserver.yaml
          ...
          command:
          - /hyperkube
          - apiserver
          ...
          - --oidc-issuer-url=<oidcServerURL>
          - --oidc-client-id=<oidcClientID>
          - --oidc-username-claim=email
          - --oidc-groups-claim=groups
          # for self sign cert or custom ca
          #- --oidc-ca-file=/etc/kubernetes/pki/rootca.pem
          systemctl restart kubelet
      3) You need to setup role binding for users or groupe.

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
  groups:
    - title: 'Features 🚀'
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug fixes 🐛'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Changes 🛠'
      regexp: '^.*?refactor(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
