apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: projects.kubedash.devopstales.io
spec:
  group: kubedash.devopstales.io
  scope: Namespaced
  names:
    plural: projects
    singular: project
    kind: Project
    shortNames:
      - prj
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                displayName:
                  type: string
                finalizers:
                  type: array
                  items:
                    type: string
            status:
              type: object
              properties:
                phase:
                  type: string

