---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubedash.fullname" . }}-kubedash-ini
  labels:
    app: kubedash
    {{ include "kubedash.labels" . | nindent 4 }}
data:
  kubedash.ini: |-
    ##################### KubeDash Configuration Defaults #####################
    [DEFAULT]
    app_mode = production

    #################################### Security ############################
    [security]

    # default admin password, can be changed before first start of grafana, or in profile settings
    admin_password = admin

    #################################### Database ############################
    [database]
    {{ if .Values.externalDatabase.enabled }}
    type = postgres
    host = {{ .Values.externalDatabase.host }}
    name = {{ .Values.externalDatabase.database }}
    user = root
    password = {{ .Values.externalDatabase.password | b64enc }}
    {{ else if .Values.postgresql.enabled }}
    type = postgres
    host = {{ .Release.Name }}-postgresql
    name = {{ .Values.postgresql.postgresql.database }}
    user = root
    password = {{ .Values.postgresql.postgresql.password | b64enc }}
    {{ else }}
    type = sqlite3
    {{ end }}

    {{ if .Values.redis.enabled }}
    #################################### Cache server #############################
    [remote_cache]
    # Either redis, none default is none
    type = redis

    # cache connectionstring options
    # redis: config like redis server e.g. `addr=127.0.0.1:6379,pool_size=100,db=0,ssl=false`. Only addr is required. ssl may be 'true', 'false', or 'insecure'.
    connstr = addr={{ .Release.Name }}-master:6379,pool_size=100,db=0,ssl=false 

    # prefix prepended to all the keys in the remote cache
    prefix =

    # This enables encryption of values stored in the remote cache
    encryption =

    {{ end }}
    {{ if .Values.oidc.enabled }}
    #################################### SSO Settings ###########################
    [sso_settings]

    issuer_url = {{ .Values.oidc.provider.oidcUrl}}

    client_id = {{ .Values.oidc.provider.oidcClientId }}

    secret = {{ .Values.oidc.provider.oidcSecret }}

    scope = {{ .Values.oidc.provider.oidcScopes}}

    {{ if .Values.ingress.tls.enabled }}
    callback_url = https://{{ .Values.ingress.url }}
    {{ else }}
    callback_url = http://{{ .Values.ingress.url }}
    {{ end }}
    {{ end }}
    #################################### K8S ###########################
    [k8s]
    cluster_name = {{ .Values.cluster.name }}
    api_server = {{ .Values.cluster.apiUrl }}
    {{ if .Values.cluster.caCert }}
    api_ca = {{ .Values.cluster.caCert | b64enc }}
    {{ end }}

    #################################### Monitoring Settings ###########################
    [monitoring]

    jaeger_enabled = false
    jaeger_http_endpoint = http://127.0.0.1:4318

    #################################### Plugin Settings ###########################
    [plugin_settings]
    registry = {{ .Values.plugins.registryUi.enabled }}
    helm = {{ .Values.plugins.helmDashboard.enabled }}
    gateway_api = false
    cert_manager = {{ .Values.plugins.certManager.enabled }}
    external_loadbalancer = {{ .Values.plugins.externalLoadbalancer.enabled }}