---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubedash.fullname" . }}-kubedash-ini
  labels:
    app: kubedash
    {{ include "kubedash.labels" . | nindent 4 }}
data:
  kubedash.ini: |
    ##################### KubeDash Configuration Defaults #####################
    [DEFAULT]
    app_mode = production

    #################################### Security ############################
    [security]

    # default admin password, can be changed before first start of grafana, or in profile settings
    admin_password = admin

    #################################### Database ############################
    [database]
    {{ if .Values.externalDatabase.enabled }}
    type = postgres
    host = {{ .Values.externalDatabase.host }}
    name = {{ .Values.externalDatabase.database }}
    user = root
    password = {{ .Values.externalDatabase.password }}
    {{ else if .Values.postgresql.enabled }}
    type = postgres
    host = {{ .Release.Name }}-postgresql
    name = {{ .Values.postgresql.auth.database }}
    user = {{ .Values.postgresql.auth.username }}
    password = {{ .Values.postgresql.auth.password }}
    {{ else }}
    type = sqlite3
    {{ end }}

    #################################### Cache server #############################
    [remote_cache]
    {{ if .Values.redis.enabled }}
    redis_enabled = true
    # cache connectionstring options
    redis_host = {{ .Release.Name }}-redis-master
    redis_port = 6379
    redis_db = 0
    # cache time
    short_cache_time = 60
    long_cache_time = 900
    {{ else }}
    redis_enabled = false
    # cache time
    short_cache_time = 60
    long_cache_time = 900
    {{ end }}
    {{ if .Values.oidc.enabled }}
    #################################### SSO Settings ###########################
    [sso_settings]

    issuer_url = {{ .Values.oidc.provider.oidcUrl}}

    client_id = {{ .Values.oidc.provider.oidcClientId }}

    secret = {{ .Values.oidc.provider.oidcSecret }}

    scope = {{ .Values.oidc.provider.oidcScopes}}

    {{ if .Values.ingress.tls.enabled }}
    callback_url = https://{{ .Values.ingress.url }}
    {{ else }}
    callback_url = http://{{ .Values.ingress.url }}
    {{ end }}
    {{ end }}
    #################################### K8S ###########################
    [k8s]
    cluster_name = {{ .Values.cluster.name }}
    api_server = {{ .Values.cluster.apiUrl }}
    {{ if .Values.cluster.caCert }}
    api_ca = {{ .Values.cluster.caCert | b64enc }}
    {{ end }}

    #################################### Monitoring Settings ###########################
    [monitoring]

    jaeger_enabled = false
    jaeger_http_endpoint = http://127.0.0.1:4318

    #################################### Plugin Settings ###########################
    [plugin_settings]
    registry = {{ .Values.plugins.registryUi.enabled }}
    helm = {{ .Values.plugins.helmDashboard.enabled }}
    gateway_api = false
    cert_manager = {{ .Values.plugins.certManager.enabled }}
    external_loadbalancer = {{ .Values.plugins.externalLoadbalancer.enabled }}

    #################################### End of Settings ###########################
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubedash.fullname" . }}-statsd-config
  labels:
    app: kubedash
    {{ include "kubedash.labels" . | nindent 4 }}
data:
  statsd.conf: |-
    # StatsD configuration
    # This file is used to configure the StatsD exporter.
    mappings:
      - match: "*.gunicorn.request.status.*"
        help: "gunicorn response code"
        name: "gunicorn_response_code"
        labels:
          app: "$1"
          status: "$2"
      - match: "*.gunicorn.workers"
        name: "gunicorn_workers"
        labels:
          app: "$1"
      - match: "*.gunicorn.requests"
        name: "gunicorn_requests"
        labels:
          app: "$1"
      - match: "*.gunicorn.request.duration"
        name: "gunicorn_request_duration"
        labels:
          app: "$1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubedash-gunicorn-dashboard
  labels:
    grafana_dashboard: "1"
    app: kubedash
    {{ include "kubedash.labels" . | nindent 4 }}
data:
  kubedash-gunicorn-dashboard.json: |-
    {
      "__inputs": [
        {
          "name": "DS_PROMETHEUS",
          "label": "Prometheus",
          "description": "",
          "type": "datasource",
          "pluginId": "prometheus",
          "pluginName": "Prometheus"
        }
      ],
      "__requires": [
        {
          "type": "grafana",
          "id": "grafana",
          "name": "Grafana",
          "version": "6.7.0"
        },
        {
          "type": "panel",
          "id": "graph",
          "name": "Graph",
          "version": ""
        },
        {
          "type": "datasource",
          "id": "prometheus",
          "name": "Prometheus"
        }
      ],
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "description": "Kubernetes cluster monitoring with Prometheus and Grafana",
      "editable": true,
      "gnetId": 16163,
      "graphTooltip": 0,
      "id": null,
      "iteration": 16163,
      "links": [],
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "${DS_PROMETHEUS}",
          "description": "",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 2,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
              "interval": "",
              "legendFormat": "{{`{{`}}instance{{`}}`}}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "CPU Usage",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "percent",
              "label": null,
              "logBase": 1,
              "max": "100",
              "min": "0",
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        },
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": "${DS_PROMETHEUS}",
          "description": "",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 12,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 4,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "expr": "sum by (job) (rate(container_cpu_usage_seconds_total{container!=\"\",pod!=\"\",namespace!=\"\"}[5m]))",
              "interval": "",
              "legendFormat": "{{`{{`}}job{{`}}`}}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Container CPU Usage",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "format": "percent",
              "label": null,
              "logBase": 1,
              "max": "100",
              "min": "0",
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        }
        /* The full dashboard JSON is too large to include fully here inline, but you can fetch the full JSON from the link and replace the content here */
      ],
      "refresh": "15s",
      "schemaVersion": 26,
      "style": "dark",
      "tags": [
        "kubernetes",
        "cluster",
        "monitoring"
      ],
      "templating": {
        "list": [
          {
            "current": {
              "selected": false,
              "text": "All",
              "value": "$__all"
            },
            "hide": 0,
            "label": "Namespace",
            "name": "namespace",
            "options": [],
            "query": "label_values(namespace)",
            "refresh": 1,
            "regex": "",
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Kubernetes Cluster Monitoring",
      "uid": "k8s-cluster-monitoring",
      "version": 1
    }
{{ end }}