apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "kubedash.fullname" . }}
  labels:
    app: kubedash
    {{- include "kubedash.labels" . | nindent 4 }}
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . |  sha256sum | trunc 63 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: "100%"
{{- if gt .Values.replicas 1.0 }}
      maxUnavailable: "50%"
{{- else }}
      maxUnavailable: "100%"
{{- end }}
  selector:
    matchLabels:
      app: kubedash
      {{- include "kubedash.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: kubedash
        {{- include "kubedash.labels" . | nindent 8 }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . |  sha256sum | trunc 63 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubedash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        env:
          - name: TZ
            value: {{ .Values.TimeZone }}
          - name: FLASK_CONFIG
            value: "{{ .Values.flaskConfig }}"
{{- if or (eq .Values.logLevel "DEBUG") (eq .Values.logLevel "HIGH") }}
          - name: VERBOSE_LOG
            value: "True"
{{- end }}
        envFrom:
        livenessProbe:
          httpGet:
            path: /api/health/live
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 1
        ports:
        - containerPort: 5000
          protocol: TCP
          name: http
        volumeMounts:
{{- if .Values.persistence.enabled }}
        - name: cache
          mountPath: "/code/kubedash/database"
{{- end }}
        - mountPath: /code/kubedash/kubedash.ini
          name: kubedash-ini
          subPath: kubedash.ini
{{- if .Values.monitoring.enabled }}
      - name: statsd-exporter
        image: "{{ .Values.image.statsdExporter.repository }}:{{ .Values.image.statsdExporter.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 9125
            protocol: TCP
            name: statsd-exporter
          - containerPort: 9102
            protocol: TCP
            name: prometheus-exporter
        args:
          - --statsd.mapping-config=/statsd/statsd.conf
        volumeMounts:
          - mountPath: /statsd/statsd.conf
            name: statsd-config
            subPath: statsd.conf
{{- end }}
      volumes:
{{- if .Values.persistence.enabled }}
      - name: cache
        persistentVolumeClaim:
            claimName: {{ include "kubedash.fullname" . }}-db
{{- end }}
      - configMap:
          defaultMode: 420
          name: {{ include "kubedash.fullname" . }}-kubedash-ini
        name: kubedash-ini
{{- if .Values.monitoring.enabled }}
      - configMap:
          defaultMode: 420
          name: {{ include "kubedash.fullname" . }}-statsd-config
        name: statsd-config
{{- end }}
{{- if .Values.persistence.enabled }}
      - name: db
        persistentVolumeClaim:
          claimName: {{ include "kubedash.fullname" . }}-db
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
        {{- . | toYaml | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
        {{- . | toYaml | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
        {{- . | toYaml | nindent 8 }}
{{- end }}
