{{- if and .Values.redisCommander.enabled .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubedash.fullname" . }}-redis-commander
  labels:
    app: "redis-commander"
    {{- include "kubedash.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
  selector:
    app: "redis-commander"
    {{- include "kubedash.labels" . | nindent 4 }}
{{- end }}

