apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubedash.fullname" . }}
  labels:
    app: kubedash
    {{- include "kubedash.labels" . | nindent 4 }}
spec:
  selector:
    app: kubedash
    {{- include "kubedash.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- if .Values.metrics.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubedash.fullname" . }}-metrics
  labels:
    app: kubedash
    app.kubernetes.io/component: metrics
    {{- include "kubedash.labels" . | nindent 4 }}
spec:
  selector:
    app: kubedash
    {{- include "kubedash.selectorLabels" . | nindent 4 }}
  ports:
    - name: statsd-tcp
      port: 9125
      protocol: TCP
      targetPort: 9125
    - name: statsd-udp
      port: 9125
      protocol: UDP
      targetPort: 9125
    - name: http-monitoring
      port: 9102
      protocol: TCP
      targetPort: 9102
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubedash.fullname" . }}-headless
  labels:
    app: kubedash
    {{- include "kubedash.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: kubedash
    {{- include "kubedash.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
    {{- if .Values.metrics.enabled }}
    - name: statsd
      port: 9125
      protocol: TCP
      targetPort: 9125
    - name: prometheus
      port: 9102
      protocol: TCP
      targetPort: 9102
    {{- end }}
  sessionAffinity: None
