{{- if .Values.extensionApi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubedash.fullname" . }}-extension-api
  labels:
    app: kubedash
    app.kubernetes.io/component: extension-api
    {{- include "kubedash.labels" . | nindent 4 }}
spec:
  selector:
    app: kubedash
    {{- include "kubedash.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: {{ .Values.extensionApi.servicePort }}
      targetPort: {{ .Values.extensionApi.targetPort | default .Values.service.port }}
      protocol: TCP
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end }}

