apiVersion: v1
kind: Namespace
metadata:
  name: kubedash
  labels:
    app: kubedash
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubedash-admin
  namespace: kubedash
  labels:
    app: kubedash
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubedash-admin
  labels:
    app: kubedash
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubedash-admin
  labels:
    app: kubedash
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubedash-admin
subjects:
- kind: ServiceAccount
  name: kubedash-admin
  namespace: kubedash