services:
  nginx:
    container_name: kubedash-proxy
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx-kubedash.conf:/etc/nginx/conf.d/nginx-kubedash.conf
      - ./config/kubedash.k3s.intra.pem:/etc/nginx/kubedash.k3s.intra.pem
      - ./config/kubedash.k3s.intra-key.pem:/etc/nginx/kubedash.k3s.intra-key.pem
    extra_hosts:
      - "host.docker.internal:host-gateway"