services:
  neo4j:
    container_name: kubedash-neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/Password1
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
