services:
  neo4j:
    container_name: kubedash-neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - "NEO4J_AUTH=kubedash/password"
      - NEO4JLABS_PLUGINS=["apoc", "n10s", "graph-data-science"]