services:
  postgresql:
    container_name: kubedash-postgresql
    image: postgres:13.12
    environment:
      POSTGRES_DB: kubedash
      POSTGRES_USER: kubedash
      POSTGRES_PASSWORD: kubedash
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Europe/Budapest
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    logging:
      options:
        max-size: "10k"
        max-file: "3"
  pgadmin:
    image: dpage/pgadmin4
    container_name: kubedash-pgadmin4
    restart: always
    ports:
      - "8001:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kubedash@devopstales.intra
      PGADMIN_DEFAULT_PASSWORD: kubedash
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgresql-data: {}
  pgadmin-data: {}