services:
  redis:
    container_name: kubedash-redis
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379
    command: ["redis-server"]

  redis-ui:
    container_name: kubedash-redis-ui
    image: patrikx3/p3x-redis-ui
    volumes:
      - ./config/redis-ui.json:/settings/.p3xrs-conns.json
    ports:
      - 8002:7843

  redis-commander:
    container_name: kubedash-redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:kubedash-redis:6379
      - REDIS_COMMANDER_HTTP_AUTH_USER=
      - REDIS_COMMANDER_HTTP_AUTH_PASSWORD=
      - REDIS_COMMANDER_HTTP_AUTH=no
      - REDIS_COMMANDER_NOAUTH=true
    ports:
      - "8004:8081"
    user: redis