services:
  redis:
    container_name: kubedash-redis
    image: redis:latest
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379
    command: ["redis-server"]

  redis-ui:
    container_name: kubedash-redis-ui
    image: patrikx3/p3x-redis-ui
    volumes:
      - ./config/redis-ui.json:/settings/.p3xrs-conns.json
    ports:
      - 8002:7843