name: "Release kubectl"

on:
  push:
    tags:
      - "*.*"

jobs:
  goreleaser:
    name: Create Release
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.2'
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          workdir: src/kdlogin
          args: release -f .goreleaser.yaml --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
      - name: test
        run: |
          ls -laF
          cd src/kdlogin
          ls -laF
          ls -laF dist

# https://github.com/orgs/community/discussions/26274
