name: Release helm chart 

on:
  push:
    tags:
      - "*.*"

jobs:
  build-kubedash:
    name: Build kubedash
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      id-token: write
      security-events: write
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Run helm-docs
        uses: losisin/helm-docs-github-action@v1
        with:
          chart-search-root: deploy/charts

      - name: add repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add ubernetes-sigs https://kubernetes-sigs.github.io/metrics-server/

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          skip_existing: false
          packages_with_index: true
          charts_dir: deploy/
          config: deploy/charts/cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
